---
- hosts: 172.31.17.197
  become: yes
  tasks: 
  - name: i want to execute linux command directly by playbook
    command: hostname -f
    register: myresult

  - name: i want to display my first task result
    debug:
       msg: "{{ myresult}}"
