---
- hosts: 172.31.17.197
  become: yes
  tasks:
  - name: install git,tree, wget
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - git
      - tree
      - wget 
  
  
  
    


