---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks: 
  - name:  i want to install webserver on only anible  ubuntu node
    apt:
      name: "{{mywebpackforubntu}}"
      state: present
    when: ansible_os_family =="Debian"

  - name: i want to start webserver on only ansible ubuntu node
    service:
      name: "{{mywebpackforubntu}}"
      state: started
    when: ansible_os_family =="Debian"


  - name: i want to install webserver on only ansible Redhat node
    yum:
      name: "{{mywebpackforredhat}}"
      state: present
    when: ansible_os_family =="RedHat"

  - name: i want to start webserver on only ansible Redhat node
    service:
       name: "{{mywebpackforredhat}}"
       state: started
    when: ansible_os_family =="RedHat"